name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Update submodules
        run: |
          git submodule update --init --recursive
          git submodule update --remote
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Create symlinks for README files (up to 2 levels deep)
        run: |
          cd docs
          ln -sf ../README.md index.md
          for readme in ../*/README.md ../*/*/README.md; do
            if [ -f "$readme" ]; then
              dir=$(dirname "$readme")
              rel_path=${dir#../}
              link_name=$(echo "$rel_path" | tr '/' '_' | tr '[:upper:]' '[:lower:]').md
              ln -sf "$readme" "$link_name"
            fi
          done
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements.txt
      - name: Convert C++ files to Markdown
        run: python scripts/convert.py src/codesignal docs
      - name: List docs contents
        run: ls -R docs
      - run: mkdocs gh-deploy --force
